---
# tasks file for buildtools
- name: install buildtools
  package:
    name: "{{ buildtools_packages[ansible_distribution]
          | default (buildtools_packages['default'] ) }}"
    state: "{{ buildtools_package_state }}"
