---
- name: Prepare
  hosts: all
  gather_facts: no

  roles:
    - robertdebock.bootstrap

  tasks:
    - name: run gcc
      shell: gcc --version > gcc.version
      args:
        creates: gcc.version
