---
- name: Converge
  hosts: all
  gather_facts: false
  become: yes

  roles:
    - robertdebock.bootstrap
    - ansible-role-buildtools

  tasks:
    - name: run gcc
      shell: gcc --version > gcc.version
      args:
        creates: gcc.version
