---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.buildtools

  tasks:
    - name: run gcc
      shell: gcc --version > gcc.version
      args:
        creates: gcc.version
