---
- name: Converge
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-buildtools

  tasks:
    - name: run gcc
      shell: gcc --version > gcc.version
      args:
        creates: gcc.version
